version: '3.4'

networks:
 dev:
  driver: bridge

services:
  northwindapi:
    image: ${DOCKER_REGISTRY-}northwindapi
    ports:
     - "8000:80"
    build:
      context: .
      dockerfile: NorthwindApiApp/Dockerfile
    networks: 
     - dev

  northwindmvc:
    image: ${DOCKER_REGISTRY-}northwindmvc
    ports:
     - "8001:80"
    build:
      context: .
      dockerfile: NorthwindMvc/Dockerfile
    depends_on: 
     - northwindapi
    networks: 
     - dev

  app_db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
     - "8002:1433"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Haemorr_8421
    networks: 
     - dev
