version: '3.7'

networks:
 dev:
  driver: bridge

services:
 app_db:
  image: "mcr.microsoft.com/mssql/server"
  container_name: sqlserver
  ports:
   - "8002:1433"
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=Haemorr_8421
  restart: always
  networks: 
   - dev

 northwind-app:
  image: northwind
  depends_on:
   - "app_db"
  container_name: sad_colden
  ports:
   - "8088:80"
  build:
   context: .
   dockerfile: Dockerfile
  networks: 
   - dev
  