//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Northwind.Services.EntityFrameworkCore.Blogging.Context;

//#nullable disable

//namespace Northwind.Services.EntityFrameworkCore.Blogging.Migrations
//{
//    [DbContext(typeof(BloggingContext))]
//    [Migration("20220712140536_BlogArticleProducts")]
//    partial class BlogArticleProducts
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.6")
//                .HasAnnotation("Relational:MaxIdentifierength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1, 1);

//            modelBuilder.Entity("Northwind.Services.Blogging.BlogArticle", b =>
//                {
//                    b.Property<int>("ArticleId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("article_id");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1, 1);

//                    b.Property<int>("EmployeeId")
//                        .HasColumnType("int")
//                        .HasColumnName("employee_id");

//                    b.Property<DateTime>("PublishDate")
//                        .HasColumnType("datetime2")
//                        .HasColumnName("publish_date");

//                    b.Property<string>("Text")
//                        //.HasMaxength(255)
//                        .HasColumnType("nvarchar(255)")
//                        .HasColumnName("text");

//                    b.Property<string>("Title")
//                        //.HasMaxength(40)
//                        .HasColumnType("nvarchar(40)")
//                        .HasColumnName("title");

//                    b.HasKey("ArticleId");

//                    b.ToTable("BlogArticles");
//                });

//            modelBuilder.Entity("Northwind.Services.Blogging.BlogArticleProduct", b =>
//                {
//                    b.Property<int>("ArticleProductId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("article_product_id");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleProductId"), 1, 1);

//                    b.Property<int>("ArticleId")
//                        .HasColumnType("int")
//                        .HasColumnName("article_id");

//                    b.Property<int>("ProductId")
//                        .HasColumnType("int")
//                        .HasColumnName("product_id");

//                    b.HasKey("ArticleProductId");

//                    b.ToTable("BlogArticleProducts");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
